pub const WAEB_VERSION: &str = "1.0.0-draft.1";

pub const SCHEMAS: &[(&str, &[u8])] = &[
    (
        "acquisition-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/acquisition-1.0.schema.json"
        )),
    ),
    (
        "acquisition-event-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/acquisition-event-1.0.schema.json"
        )),
    ),
    (
        "capabilities-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/capabilities-1.0.schema.json"
        )),
    ),
    (
        "chat-completeness-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/chat-completeness-1.0.schema.json"
        )),
    ),
    (
        "common-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/common-1.0.schema.json"
        )),
    ),
    (
        "completeness-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/completeness-1.0.schema.json"
        )),
    ),
    (
        "dataset-inventory-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/dataset-inventory-1.0.schema.json"
        )),
    ),
    (
        "evidence-record-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/evidence-record-1.0.schema.json"
        )),
    ),
    (
        "index.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/index.json"
        )),
    ),
    (
        "media-record-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/media-record-1.0.schema.json"
        )),
    ),
    (
        "raw-record-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/raw-record-1.0.schema.json"
        )),
    ),
    (
        "records/account-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/records/account-1.0.schema.json"
        )),
    ),
    (
        "records/chat-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/records/chat-1.0.schema.json"
        )),
    ),
    (
        "records/chat-list-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/records/chat-list-1.0.schema.json"
        )),
    ),
    (
        "records/contact-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/records/contact-1.0.schema.json"
        )),
    ),
    (
        "records/event-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/records/event-1.0.schema.json"
        )),
    ),
    (
        "records/generic-entity-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/records/generic-entity-1.0.schema.json"
        )),
    ),
    (
        "records/message-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/records/message-1.0.schema.json"
        )),
    ),
    (
        "records/participant-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/records/participant-1.0.schema.json"
        )),
    ),
    (
        "records/relation-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/records/relation-1.0.schema.json"
        )),
    ),
    (
        "seal-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/seal-1.0.schema.json"
        )),
    ),
    (
        "signer-1.0.schema.json",
        include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/wa-evidence-bag/v1/schemas/signer-1.0.schema.json"
        )),
    ),
];

pub fn core_seal_tag_paths() -> Vec<String> {
    let mut paths = vec!["bag-info.txt".to_owned(), "bagit.txt".to_owned()];
    paths.extend(SCHEMAS.iter().map(|(path, _)| format!("schemas/{path}")));
    paths.push("signatures/signer.json".to_owned());
    paths.sort_by(|left, right| left.as_bytes().cmp(right.as_bytes()));
    paths
}
